#pragma config(Sensor, S1,     L1,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     L2,             sensorEV3_Color)
#pragma config(Sensor, S3,     U1,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     U2,             sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                          - Wait for Dark -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your taskbot forward until it detects a dark surface.                               *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/


void motors(int a, int b, int forTime) {
	motor[motorA] = a;
	motor[motorB] = b;
	
	wait1Msec(forTime);
}

task main()
{
	wait1Msec(50);                         // The program waits 50 milliseconds to initialize the light sensor.
	
	/* ================================================ *
	 * Go forward from start until you hit the lego box 
	 * ================================================ */

	while(SensorValue[U1 > 5]) { // get most of the way to the wall
		motors(100, 100, 0);
	}

	motors(25, 25, 500); // get the rest of the way there
	
	/* ================================================ *
	 * Find the line to follow and then do so
	 * ================================================ */
	
	motors(-75, -75, 1000); // backup from the wall
	
	motors(-15, 15, 700); // turn left to, hopefully, face the line
	
	motors(50, 50, 1000); // go forward for a while
	
	int left = 50, right = 50; // follow line
	
	while(SensorValue[U1 > 5]) {
		motors(left, right, 10); // default is go
		
		if(SensorValue[L1] == 5) // otherwise if the left sees red, adjust left
			left--; // this may not be enough (left -= 40 ?)
		if(SensorValue[L2] == 5) // otherwise if the right sees red, adjust right
			right--; // this may not be enough (right -= 40 ?)
	
		if((SensorValue[L1] != 5) && (SensorValue[L2] != 5)) // if neither see red, reset to normal speed
		{
			left = 50;
			right = 50;
		}
	}

	/* ================================================ *
	 * Get into configuration zone
	 * ================================================ */
	
	motors(15, -15, 700); // turn right (Alernatively try `motors(100, 40, 500)` or similar to turn while continuing forward)
	
	while(SensorValue[U1 > 5]) { // stop infront of the wall
		motors(50, 50, 0);
	}
	
	while((SensorValue[L1] != 5) || (SensorValue[L2] != 5)) { // backup until red
		motors(-100, -100, 0);
	}
	
	while((SensorValue[L1] != 1) || (SensorValue[L2] != 1)) { // continue backup until black line
		motors(-100, -100, 0);
	}
	
	motors(15, -15, 700); // turn right
	
	while(SensorValue[U1 > 5]) { // run towards the wall
		motors(50, 50, 0);
	}
		
	motors(-15, 15, 700); // turn left
	
	while(SensorValue[U1 > 5]) { // run into the wall
		motors(50, 50, 0);
	}
	
	motors(0, 0, 0); // stop
}

/*NOTE

Instead of stopping the motors when you reach a dark surface, you could also count them using a
variable for the line counting challenge.

*/
